### PR TITLE
Attempt to fix travis CI

### PR DESCRIPTION
**Pull request by npars**
- Fail fast when any command in the script fails
- Use new devkitpro deb

### CODE REVIEW

**Comment by npars** [comment]
No idea if this will work 🤞

**Comment by Lokathor** [comment]
If possible, i think we should move it all to github actions instead.

**Comment by npars** [comment]
I was thinking the same thing, I looked into it briefly. Looks like I could
whip up a CI Dockerfile that could be run through both GitHub Actions and
locally.

Only issue is that publishing to GitHub pages might not be as easy. But
maybe we can worry about that after we get a working build.

**Comment by Lokathor** [comment]
https://github.com/rust-console/min-gba/blob/main/.github/workflows/rust.yml

This should work as a starting point.

I think we want to just pull out the book part. I keep writing the same few pages and stopping. It'd be better to just focus on the quality of the crate itself (which will hopefully go up with rustc 1.51 min_const_generics, and also perhaps someday proper bitfields).

**Pull request closed without merging**
