### PR TITLE
Properly finish documentation for the `save` module.

### LINKED ISSUE #114: docs in save mod for "Using save media"
In the PR, these docs were incomplete. however, the PR had been sitting a while so i didn't want to hold it up further. we should still document it in the future.

### PR DESCRIPTION
**Pull request by Lymia**
Sorry, I seem to have missed this. Fixes #114.

### CODE REVIEW

**Comment by Lokathor** [comment]
if `prepare_write` is important, should we use type system stuff to make sure that you *must* call it? We could make the method consume `self` and then return a `PreparedSaveAccess` object instead, which then has the actual operations on it.

Personally, I don't think that I'll ever write a GBA game for any target other than an emulator, so I don't have a strong opinion about interacting with strange save media types. However, type system shenanigans are generally a nifty trick that the embedded working group uses to great effect so that widgets always get their commands in the correct order without causing runtime overhead. If it leads to increased correctness, I think that we should try to use such a pattern here as well.

not that it blocks this PR, but we could open an issue about it and get to it later.

**Comment by Lymia** [comment]
That's an API I hadn't considered before. It's a good idea. `prepare_write` is strange because it's only required on a subset of storage media, but... well. That storage media is also the one with the largest size, so I expect it to be used relatively often. This also matters on emulator because (at least the emulator I use) also emulate the access speeds of storage media, meaning... well. It's kinda relevant to optimization even on emulator.

**Comment by Lokathor** [comment]
ah, which emulator is that?

**Comment by Lymia** [comment]
MGBA. See here: https://github.com/mgba-emu/mgba/blob/master/src/gba/savedata.c#L18-L27

**Comment by Lokathor** [comment]
Okay. Well I will merge this now so we have docs on the crate as is, and we can improve things later.

**Pull request merged**
