### PR TITLE
Bump voladdress version + reword

### PR DESCRIPTION
**Pull request by nicopap**
I'm opening the PR for discussion. I did the modifications mostly for myself, but it would be bad to not provide upstream with a PR.

Before merging there is still more work to be done on the fixed point documentation file, and maybe some more moving macros to blanket implementations. But I'd like feedback first on what I'm doing.

### CODE REVIEW

**Comment by Lokathor** [comment]
In my spare workings of the GBA I've tried using the `voladdress` crate less and I've also tried using a "next version" with more precise address types for better accuracy.

* https://github.com/Lokathor/niobium, ZST specific types per address.
* https://github.com/Lokathor/rubidium, has a "next version of `voladdress`"

Neither path seemed clearly better than the other, though I suppose I favored `rubidium` more just because it's probably easier to learn about a handful of types and then reuse that knowledge when looking at a new address. On the other hand, it's neat to have ZST types, but I'm not sure how often you'd pass an address, which is the only time it'd matter I think.

**Comment by Lokathor** [comment]
Also note that, most of the text in src-bak is... well, it isn't really the best quality right now and so I'm not sure how much it needs to be kept up to date. I've wanted to split out the gba learning book from the gba crate repo, but haven't had the time to make a lot of progress there, because I keep doing other projects in the mean time.

**Comment by nicopap** [comment]
I understand. I'll look into the libraries you linked when I have some time. If they are what they look like at first glance, they are going to be very usefull. I'll simply see how I use them and go on from there.

I'm moving an old C GBA project to Rust for fun. Those far it has been fairly easy. Plus this is the oportunity to learn about an aspect of Rust I've never used before.

**Comment by Lokathor** [comment]
i think rubidium is probably the best path forward, and then the ZST version could be done on top if a person wanted to do that. Having all the ZST stuff is an idea i got from the embedded working group and I only kinda like it. It works well for them because they want code that's generic over different devices (like "this function works for anything with a serial port"), but when the code is specific to just a single device it feels like it's just complicating the situation for no gain.

**Comment by nicopap** [comment]
I've had a glance at `rubidium` and `niobium` now. Here is my feedback.

In short:
* `voladdress` with the `gba` register addresses is enough for me, so I might content myself to fork `gba` and use `voladdress 0.3`
* To use `rubidium` I would need to implement `Mode0` which is not a big deal, but still some work
* I see the idea behind `niobium`, but it would be sounder to implement it as a higher-level API on top of something simpler

I don't see myself doing anything in any direction in the short term, so I'll keep things as they are now.

### rubidium

`rubidium` is pretty much `voladdress` with the gba register definitions.  Looking at the implementation, `rubidium` is easier to understand for sure.  Although `voladdress` is not complex.


### niobium

The `niobium` API seems clumsy.

I figured that a higher-level API in rust based on singletons could be useful for the GBA, because of how modifying `DSPCNT` changes VRAM layout. eg: `DSPCNT` could have a method that at the same time sets video mode and returns a handler to VRAM, having a different type depending on the video mode. And you would have to consume the handler to change video mode.

However, even if `niobium` has a singleton, it really doesn't take advantage of it. It's just a clumsier way to do what `rubidium` does.


### Block addresses

I use Mode0. I find `voladdress::VolBlock` to be very useful to define ranges of memory I can iterate over to set sprites and tile maps.

There is no equivalent in `rubidium`. I see that in `rubidium::Mode{3,4,5}` the API looks like: `screen.x(0).y(34)`.

I guess it's just up to me to implement Mode0 and see how the API turns out. I don't think there is any obstacle to make the API as convinient or more than `VolBlock`.


### Note on register definition

I see the main difficulty is in defining the data structures for the registers.  In my old C code (disclaimer: it's very old) I can find:

```c
typedef struct s_dispstatcnt {
    u16 vBlankStat : 1;
    u16 hBlankStat : 1;
    u16 vCountStat : 1;
    u16 vBlankIntrpt : 1;
    u16 hBlankIntrpt : 1;
    u16 vCountIntrpt : 1;
    u16 undef1 : 2;
    u16 vCountSetup : 8;
} dispStatCnt;
#define DISPSTAT_CNT ((volatile dispStatCnt*) 0x4000004)
```

It's really just a C feature that Rust soundly chooses not to hardcode in the compiler. As a result the rust programmer is left to implement it themselves.

I find your approach in `rubidium` (didn't check in other crates) to be nice as it exposes a clean API. On top of that, even if it relies heavily on macros (to not say it's a macro mess), the code is understandable.

I found on crates.io [a crate for mmio registers](https://crates.io/crates/tock-registers).

**Comment by Lokathor** [comment]
This eventually got handled in the big update to 0.4, so I'll close it.

**Pull request closed without merging**
