### PR TITLE
Adapt to new asm syntax

### PR DESCRIPTION
**Pull request by nicopap**
Addresses #92 (although, not in a satisfying way)

### CODE REVIEW

**Comment by Lokathor** [comment]
I can check this out in 9-10 hours at soonest.

However, I'll ask ahead of time, could you switch the code all the way to using the new asm syntax? The actual ASM blocks are simple enough that they should be resistant to small changes to the new style syntax during the final stabilization process. Generally you're just calling a single swi instruction, maybe with some args.

**Comment by nicopap** [comment]
I'll switch to the new syntax them.

**Comment by nicopap** [comment]
I'll also take the time to update the 02-bios.md manual entry. Since the new syntax renders the bits on `asm` obsolete (which is very good news)

**Comment by Lokathor** [comment]
That sounds good. The state of the book is kinda up in the air, and ive been developing some other gba stuff in other repos, and I've never quite had the time to integrate it all into this repo.

**Comment by Lokathor** [comment]
Looks good. Should we merge it here or did you have anything else you wanted to do?

**Comment by nicopap** [comment]
I just checked the examples in release mode. Seems everything is working. I think we can merge it.

Thank you for this amazing project and the quick review!

**Pull request merged**
