### PR TITLE
Add an example for directly modifying pixels on mode 3 realtime during game vs loading a pixel array directly.

### PR DESCRIPTION
**Pull request by EvanTheProgrammer**

### CODE REVIEW

**Comment by Lokathor** [comment]
This looks good, and having your own credit on the file is totally fine, but before I can merge it I would need you to add it under the same license as the rest of the code in the repo (`Zlib OR Apache-2.0 OR MIT`), for simplicity to users of the crate. Documentation and config files and other non-code files can be `CC0` on occasion, but I'd like all code files to have an identical license.

**Comment by EvanTheProgrammer** [comment]
I have updated to MIT licence

**Comment by Lokathor** [comment]
Oh, sorry that I was unclear. The `OR` parts mean that the crate is currently available under any of the three licenses and the _user accepting the code_ gets to pick. So you'd have to contribute the file under the full three-license-choice thing. Just like it says in the `license` file of this repo's `Cargo.toml`.

More simply: you can remove the mention of any particular license from the file and then the file would default to being under the same license as the rest of the repository under [GitHub's TOS](https://github.com/github/site-policy/blob/main/Policies/github-terms/github-terms-of-service.md#6-contributions-under-repository-license) for how contributions work.

**Comment by EvanTheProgrammer** [comment]
I have removed the licence part.

**Pull request merged**
