### PR TITLE
Switch to Github Actions

### PR DESCRIPTION
**Pull request by npars**
- Remove travis ci config
- Add Github action for CI

### CODE REVIEW

**Comment by npars** [comment]
@Lokathor I think I'm getting relatively close here, it's currently failing with the following error:
```
   Compiling gba v0.4.0-pre1 (/__w/gba/gba)
error[E0463]: can't find crate for `std`
Error:   |
  = note: the `thumbv4-none-agb-29733657473576968` target may not be installed
  ```

**Comment by Lokathor** [comment]
There's no `std` available on gba. Everything should be `#![no_std]` though. You won't be able to use `cargo test` though.

**Comment by Lokathor** [comment]
uhhh github actions doesn't appear to be running on the branch despite you having put in a github actions file, though i'm not sure why.

**Comment by npars** [comment]
@Lokathor I'm wondering if it needs to be merged in first or enabled somewhere? Maybe disabled to prevent random people from creating PRs and using up your. action minutes?

**Comment by npars** [comment]
It's running over in my repo: https://github.com/npars/gba/runs/1891894285?check_suite_focus=true

**Comment by Lokathor** [comment]
Ah, so it is.

In terms of CI config, I think that these days we can stop using `cargo-xbuild` and just use the `thumbv4t-none-eabi` target via the `--target` flag, if we also include `-Zbuild-std=core`

You'd steal a little of the CI from here:
https://github.com/rust-console/min-gba/blob/main/.github/workflows/rust.yml

and a little bit of the default cargo config from here:
https://github.com/rust-console/min-gba/blob/main/.cargo/config.toml

Of course, i haven't commented that process much at all so if you didn't wanna mess with it too much i'd understand.

**Comment by npars** [comment]
@Lokathor [Got it working this time](https://github.com/npars/gba/runs/1891932348), should be good to merge at this point.

I think I'd rather get this merged as is, then try to optimize it with another PR. Looking at the min-gba repo, does that mean we can also drop the dependency on the devkitpro libraries?

**Comment by Lokathor** [comment]
We can, we just need arm binutils from apt-get

**Pull request merged**
