### PR TITLE
Add Serial and GPIO registers and implement embedded_hal traits

### PR DESCRIPTION
**Pull request by mogenson**
Use VolAddress and phantom_fields to populate the SIOCNT, RCNT, and
SIODATA8 registers. Implement embedded_hal serial traits around an empty
SioSerial struct.

Here is an example serial echo program that has been tested with a USB to UART adapter soldered to a GBA link cable.

```
#![no_std]
#![no_main]

use embedded_hal::prelude::*;
use gba::io::sio::{SioSerial, BaudRate};
use panic_abort as _;

#[no_mangle]
pub fn main() {
    let mut serial = SioSerial;
    SioSerial::init(BaudRate::Bps115200);

    loop {
        if let Ok(c) = nb::block!(serial.read()) {
            nb::block!(serial.write(c)).ok();
        }
    }
}
```

### CODE REVIEW

**Comment by Lokathor** [comment]
This is really cool!

One change I would make is to make it an optional dependency and `cfg` out the serial stuff when the dependency isn't used. Since plenty of games won't use the serial port, no need for them to download and build the extra stuff.

**Comment by mogenson** [comment]
How about a feature named "embedded_hal"? If additional traits for timers and digital pins were added in the future, you could use a wide range of no_std crates and drivers that depend on embedded-hal. These traits could be hidden behind the "embedded_hal" feature to only expose them if required.

I included the UART echo program as an example demonstrating the feature flag and serial API.

For context, I have an ESP8266 WiFi module wired to a link cable. The AT command set of this chip is supported by an embedded-hal driver. This PR is a first step towards bringing networking to my GBA.

**Comment by Lokathor** [comment]
I thought I'd posted a reply but I guess I didn't hit the button.

That all sounds good. I like the name `serial` which pulls in the extra stuff, most games probably dont need serial port support.

**Comment by mogenson** [comment]
Ok, I renamed the `embedded_hal` feature flag to `serial`. Tested the `uart_echo` example on a physical GBA to make sure it still works.

**Comment by Lokathor** [comment]
Okay, should I merge it?

(We can ignore the CI, I've been meaning to replace it with github actions stuff for ages.)

**Comment by mogenson** [comment]
I'm ready to merge!

**Pull request merged**
