### PR TITLE
move to a tri-license (adds Zlib and MIT options)

### PR DESCRIPTION
**Pull request by Lokathor**
I noticed that currently we only offer the Apache-2.0 license. This PR allows Zlib and MIT licensing options.

This PR will need approval from past contributors, so get ready for some pings yall:
* [x] @Lokathor 
* [x] @Sp00ph
* [x] @Shadlock0133
* [x] @Dhs92
* [x] @ketsuban
* [x] @mogenson
* [x] @Lymia
* [x] @Ruin0x11
* [x] @eevee
* [x] @npars
* [x] @parasyte
* [x] @sphinxc0re
* [x] @felixjones
* [x] @nicopap

### CODE REVIEW

**Comment by Dhs92** [comment]
✅

**Comment by Shadlock0133** [comment]
I only did a 1-line readme change, so I don't think it counts, but in any case: ✅

**Comment by Dhs92** [comment]
> I only did a 1-line readme change, so I don't think it counts, but in any case: ✅

Same

**Comment by Sp00ph** [comment]
✅

**Comment by ketsuban** [comment]
✅

**Comment by felixjones** [comment]
✅

**Comment by Ruin0x11** [comment]
✔️

**Comment by parasyte** [comment]
Love it. ✅

**Comment by npars** [comment]
✅

Should the README mention that the whole project is multi-licensed, so people don't think the licenses apply to certain subsets of the code?

**Comment by sphinxc0re** [comment]
✅

**Comment by Lokathor** [comment]
@npars I think that, since 98% of the Rust ecosystem is Apache-2.0/MIT, people are used to the idea by now.

**Comment by Lymia** [comment]
:white_check_mark:

**Comment by eevee** [comment]
:heavy_check_mark:

**Comment by mogenson** [comment]
✓

**Comment by Lokathor** [comment]
**Update:** Now we've got everyone's sign off except for @nicopap. I'll leave this open for a week or so, to give them time to respond, but otherwise I'll just merge it because they seem to only show up on github occasionally. I don't want to accept any other new PRs until this is totally resolved so I'd like to have it all sorted out sooner rather than later.

**Comment by nicopap** [comment]
All green for me, approved. Sorry for the late response

**Comment by Lokathor** [comment]
no worries at all! people have busy lives and such.

**Pull request merged**
